In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold
from sklearn.utils import resample
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
def validacionCruzada(X_train,y_train,k):
    print ('\n ----------------------\n')
    print ('\n Validación cruzada \n')
    kf = KFold(n_splits=k)
    print ('\n X \n')
    for train, test in kf.split(X_train):
        print(X_train[train], X_train[test])
    print ('\n y \n')
    for train, test in kf.split(X_train):
        print(y_train[train], y_train[test])

def dejaUnoFuera(X_train,y_train):
    print ('\n ----------------------\n')
    print ('\n LeaveOneOut')
    loo = LeaveOneOut()
    print (loo.get_n_splits(X_train))
    print ('\n X \n')
    for i, (train_index, test_index) in enumerate(loo.split(X_train)):
        print('\n',i,X_train[train_index], X_train[test_index])
    print ('\n y \n')
    for i, (train_index, test_index) in enumerate(loo.split(X_train)):
        print('\n',i,y_train[train_index], y_train[test_index])

def bootstrap(X_train,y_train,nc,m):
    print ('\n ----------------------\n')
    print ('\n Bootstrap')
    print ('\n X \n')
    for i in range(nc):
        train = resample(X_train, n_samples = m)
        test = np.array([x for x in X_train if x not in train])
        print ('train',train,'test',test)
    print ('\n y')
    for i in range(nc):
        train = resample(y_train, n_samples = m)
        test = np.array([x for x in y_train if x not in train])
        print ('train',train,'test',test)
    print ('\n')

In [3]:
if __name__=='__main__':
    df = pd.read_csv('metodosDeValidacion.csv', sep=',')
    print(df)
    
    X = df[['x']].values
    y = df['y'].values
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, train_size=0.6, shuffle=False)
    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    print(f"Mean Squared Error: {mse}")

     x   y
0    1   2
1    2   4
2    3   6
3    4   8
4    5  10
5    6  12
6    7  14
7    8  16
8    9  18
9   10  20
10  11  22
11  12  24
12  13  26
13  14  28
14  15  30
15  16  32
16  17  34
17  18  36
18  19  38
19  20  40
Mean Squared Error: 5.048709793414476e-29


In [4]:
validacionCruzada(X_train,y_train,3)


 ----------------------


 Validación cruzada 


 X 

[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[1]
 [2]
 [3]
 [4]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 9]
 [10]
 [11]
 [12]] [[5]
 [6]
 [7]
 [8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] [[ 9]
 [10]
 [11]
 [12]]

 y 

[10 12 14 16 18 20 22 24] [2 4 6 8]
[ 2  4  6  8 18 20 22 24] [10 12 14 16]
[ 2  4  6  8 10 12 14 16] [18 20 22 24]


In [5]:
dejaUnoFuera(X_train,y_train)


 ----------------------


 LeaveOneOut
12

 X 


 0 [[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[1]]

 1 [[ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[2]]

 2 [[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[3]]

 3 [[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[4]]

 4 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[5]]

 5 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[6]]

 6 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[7]]

 7 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]
 [11]
 [12]] [[8]]

 8 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]] [[9]]

 9 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [11]
 [12]] [[10]]

 10 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [12]] [[11]]

 11 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] [[12]]

 y 


 0 [ 4  6  8 10

In [6]:
bootstrap(X_train,y_train,2,5)


 ----------------------


 Bootstrap

 X 

train [[ 7]
 [11]
 [ 1]
 [ 8]
 [ 8]] test [[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 9]
 [10]
 [12]]
train [[ 7]
 [ 4]
 [12]
 [ 3]
 [12]] test [[ 1]
 [ 2]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]
 [11]]

 y
train [14  2 10 22 18] test [ 4  6  8 12 16 20 24]
train [ 2 12 12 10 22] test [ 4  6  8 14 16 18 20 24]


